@startuml
skinparam linetype ortho
Node --> Optional
interface Node
MutableState --> ArrayList
MutableState --> List
class MutableState implements State
Rule --> Optional
interface Rule
Main --> LastRule
Main --> MutableState
Main --> PrefixRule
Main --> Rule
Main --> State
Main --> StringRule
Main --> SuffixRule
Main --> IOException
Main --> Files
Main --> Path
Main --> Paths
Main --> List
Main --> Optional
Main --> Collectors
class Main
StringRule --> Optional
LastRule --> Optional
MapNode --> HashMap
MapNode --> Map
MapNode --> Optional
class MapNode implements Node
PrefixRule --> Optional
SuffixRule --> Optional
State --> List
interface State
@enduml