@startuml
skinparam linetype ortho
StringRule --> MapNodeWithEverything
StringRule --> NodeWithEverything
StringRule --> Optional
class StringRule
StringRule --|> Rule
JVMPaths --> PathLike
JVMPaths --> Paths
class JVMPaths
class Err
Err --|> Result
interface Result
Locator --> Optional
interface Locator
PathLike --> IOException
PathLike --> Set
interface PathLike
FirstLocator --> Optional
class FirstLocator
FirstLocator --|> Locator
MapNodeWithEverything --> HashMap
MapNodeWithEverything --> Map
MapNodeWithEverything --> Optional
MapNodeWithEverything --> Stream
class MapNodeWithEverything
MapNodeWithEverything --|> NodeWithEverything
PrefixRule --> NodeWithEverything
PrefixRule --> Optional
class PrefixRule
PrefixRule --|> Rule
NodeWithNodes --> Map
NodeWithNodes --> Optional
NodeWithNodes --> Stream
interface NodeWithNodes
interface NodeWithType
Compiler --> Lang
Compiler --> MutableState
Compiler --> State
Compiler --> MapNodeWithEverything
Compiler --> NodeWithEverything
Compiler --> Rule
Compiler --> List
Compiler --> Map
Compiler --> Optional
Compiler --> Collectors
Compiler --> Stream
class Compiler
OrRule --> NodeWithEverything
OrRule --> List
OrRule --> Optional
class OrRule
OrRule --|> Rule
LastLocator --> Optional
class LastLocator
LastLocator --|> Locator
StripRule --> NodeWithEverything
StripRule --> Optional
class StripRule
StripRule --|> Rule
Lang --> NodeWithEverything
Lang --> LocateRule
Lang --> NodeRule
Lang --> OrRule
Lang --> PrefixRule
Lang --> Rule
Lang --> StringRule
Lang --> StripRule
Lang --> SuffixRule
Lang --> TypeRule
Lang --> List
class Lang
NodeRule --> MapNodeWithEverything
NodeRule --> NodeWithEverything
NodeRule --> Optional
class NodeRule
NodeRule --|> Rule
MutableState --> ArrayList
MutableState --> List
class MutableState
MutableState --|> State
SuffixRule --> NodeWithEverything
SuffixRule --> Optional
class SuffixRule
SuffixRule --|> Rule
JVMPath --> PathLike
JVMPath --> IOException
JVMPath --> Files
JVMPath --> Path
JVMPath --> Set
JVMPath --> Collectors
class JVMPath
JVMPath --|> PathLike
State --> List
interface State
interface NodeWithEverything extends NodeWithStrings
NodeWithStrings --> Map
NodeWithStrings --> Optional
NodeWithStrings --> Stream
interface NodeWithStrings
Rule --> Optional
interface Rule
class Ok
Ok --|> Result
LocateRule --> FirstLocator
LocateRule --> LastLocator
LocateRule --> Locator
LocateRule --> NodeWithEverything
LocateRule --> Optional
class LocateRule
LocateRule --|> Rule
Main --> Compiler
Main --> PathLike
Main --> JVMPaths
Main --> IOException
Main --> HashMap
Main --> Map
Main --> Collectors
class Main
interface MergingNode
TypeRule --> NodeWithType
TypeRule --> Optional
class TypeRule
TypeRule --|> Rule
@enduml