#include "../../../../magma/api/result/Ok.h"
#include "../../../../magma/api/result/Result.h"
#include "../../../../magma/app/error/CompileError.h"
#include "../../../../java/util/Arrays.h"
#include "../../../../java/util/List.h"
#include "../../../../java/util/regex/Pattern.h"
