#include "magma/app/compile/CompileException.h"
#include "magma/app/compile/DividingState.h"
#include "magma/app/io/source/SourceSet.h"
#include "magma/app/io/target/TargetSet.h"
#include "magma/app/io/unit/Unit.h"
#include "java/io/IOException.h"
#include "java/util/ArrayList.h"
#include "java/util/Arrays.h"
#include "java/util/List.h"
#include "java/util/Optional.h"
struct Temp {};