import magma.api.Tuple;import magma.api.stream.Stream;import magma.api.stream.Streams;import java.util.HashMap;import java.util.List;import java.util.Map;import java.util.Optional;import java.util.StringJoiner;import java.util.stream.Collectors;struct MapNode implements Node{
Map<String, String> strings;
Map<String, List<Node>> nodeLists;
Map<String, Node> nodes;
Optional<String> type;
public MapNode();
public MapNode(Optional<String> type, Map<String, String> strings, Map<String, Node> nodes, Map<String, List<Node>> nodeLists);
public MapNode(String type);
StringBuilder createEntry(String name, String content, int depth);
String toString();
String format(int depth);
Optional<Node> findNode(String propertyKey);
Node mapString(String propertyKey, Function<String, String> mapper);
Node merge(Node other);
Stream<Tuple<String, List<Node>>> streamNodeLists();
Stream<Tuple<String, Node>> streamNodes();
<K, V>Stream<Tuple<K, V>> stream(Map<K, V> map);
String display();
Node retype(String type);
boolean is(String type);
Node mapNodeList(String propertyKey, Function<List<Node>, List<Node>> mapper);
boolean hasNodeList(String propertyKey);
Node removeNodeList(String propertyKey);
Node mapNode(String propertyKey, Function<Node, Node> mapper);
boolean hasNode(String propertyKey);
Node withNode(String propertyKey, Node propertyValue);
Node withNodeList(String propertyKey, List<Node> propertyValues);
Optional<List<Node>> findNodeList(String propertyKey);
Node withString(String propertyKey, String propertyValues);
Optional<String> findString(String propertyKey);
}