#include "../../../../magma/api/Tuple.h"
#include "../../../../magma/api/stream/Stream.h"
#include "../../../../magma/api/stream/Streams.h"
#include "../../../../java/util/LinkedList.h"
#include "../../../../java/util/Optional.h"
#include "../../../../java/util/stream/Collectors.h"
#include "../../../../java/util/stream/IntStream.h"
