#include "../../../magma/app/Node.h"
#include "../../../magma/java/JavaList.h"
#include "../../../java/util/ArrayList.h"
#include "../../../java/util/List.h"
#include "../../../java/util/Optional.h"
#include "../../../java/util/function/BiFunction.h"
#include "../../../java/util/function/Predicate.h"
#include "../../../java/util/function/Supplier.h"
