#include "../../../magma/api/result/Result.h"
#include "../../../magma/api/stream/Streams.h"
#include "../../../magma/app/Node.h"
#include "../../../magma/app/error/CompileError.h"
#include "../../../java/util/ArrayList.h"
#include "../../../java/util/List.h"
