#include "../../../magma/api/result/Err.h"
#include "../../../magma/api/result/Result.h"
#include "../../../magma/app/Node.h"
#include "../../../magma/app/error/CompileError.h"
#include "../../../magma/app/error/context/StringContext.h"
#include "../../../java/util/function/Predicate.h"
