/*import magma.rule.InfixRule;*/
/*import magma.rule.OrRule;*/
/*import magma.rule.PlaceholderRule;*/
/*import magma.rule.PrefixRule;*/
/*import magma.rule.Rule;*/
/*import magma.rule.StringRule;*/
/*import magma.rule.StripRule;*/
/*import magma.rule.SuffixRule;*/
/*import magma.rule.TypeRule;*/
/*import magma.rule.divide.DivideRule;*/
/*import java.util.List;*/
