#include "../../../magma/api/option/Option.h"
#include "../../../magma/api/result/Ok.h"
#include "../../../magma/api/result/Result.h"
#include "../../../java/util/function/BiFunction.h"
#include "../../../java/util/function/Predicate.h"
