#include "../../../magma/api/stream/Stream.h"
#include "../../../magma/api/stream/Streams.h"
#include "../../../magma/app/rule/locate/Locator.h"
#include "../../../java/util/ArrayList.h"
#include "../../../java/util/List.h"
