/// Magma Compiler Driver
///
/// Unified entry point for the complete compilation pipeline.
/// Coordinates lexing, parsing, semantic analysis, HIR generation, and code generation.
/// 
/// Supports three backends:
/// - TypeScript (.ts with .d.ts declarations)
/// - JavaScript (.js for Node.js and bundlers)
/// - LLVM IR (.ll human-readable text format)

use crate::codegen_javascript::JavaScriptBackend;
use crate::codegen_llvm::LLVMBackend;
use crate::codegen_typescript::TypeScriptBackend;
use crate::diagnostics::CompilationError;
use crate::hir_lowering::HirLowering;
use crate::lexer::Lexer;
use crate::parser::Parser;
use crate::semantic::TypeChecker;
use std::fs;
use std::path::PathBuf;

/// Compilation target backend
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum CompilationTarget {
    /// Compile to TypeScript (.ts)
    TypeScript,
    /// Compile to JavaScript (.js)
    JavaScript,
    /// Compile to LLVM IR (.ll)
    LLVM,
}

impl CompilationTarget {
    /// Parse target from string
    pub fn from_string(s: &str) -> Option<Self> {
        match s {
            "ts" | "typescript" => Some(CompilationTarget::TypeScript),
            "js" | "javascript" => Some(CompilationTarget::JavaScript),
            "llvm" => Some(CompilationTarget::LLVM),
            _ => None,
        }
    }

    /// Get file extension for this target
    pub fn extension(&self) -> &'static str {
        match self {
            CompilationTarget::TypeScript => "ts",
            CompilationTarget::JavaScript => "js",
            CompilationTarget::LLVM => "ll",
        }
    }

    /// Get human-readable name
    pub fn name(&self) -> &'static str {
        match self {
            CompilationTarget::TypeScript => "TypeScript",
            CompilationTarget::JavaScript => "JavaScript",
            CompilationTarget::LLVM => "LLVM IR",
        }
    }
}

/// Compilation request with source and target information
pub struct CompilationRequest {
    /// Source code to compile
    pub source: String,
    /// Target backend
    pub target: CompilationTarget,
    /// Optional output file path
    pub output_path: Option<PathBuf>,
}

/// Compilation result with generated code and metadata
pub struct CompilationResult {
    /// Generated code
    pub code: String,
    /// Target that was compiled to
    pub target: CompilationTarget,
    /// Statistics about compilation
    pub stats: CompilationStats,
}

/// Statistics about compilation
#[derive(Debug, Clone)]
pub struct CompilationStats {
    /// Number of tokens generated by lexer
    pub token_count: usize,
    /// Number of AST nodes
    pub ast_node_count: usize,
    /// Number of HIR expressions
    pub hir_expr_count: usize,
    /// Generated code length in bytes
    pub output_bytes: usize,
}

/// Main compiler driver
pub struct MagmaDriver;

impl MagmaDriver {
    /// Compile Magma source to target backend
    pub fn compile(request: CompilationRequest) -> Result<CompilationResult, Vec<CompilationError>> {
        // Phase 1: Lexical Analysis
        let lexer = Lexer::new(&request.source);
        let tokens = lexer.tokenize()?;
        let token_count = tokens.len();

        // Phase 2: Parsing
        let parser = Parser::new(tokens);
        let program = parser.parse_program()?;
        let ast_node_count = Self::count_ast_nodes(&program);

        // Phase 3: Semantic Analysis
        let checker = TypeChecker::new();
        let symbol_table = checker.check_program(&program)?;

        // Phase 4: HIR Generation
        let lowering = HirLowering::new(symbol_table);
        let hir = lowering.lower_program(&program)?;
        let hir_expr_count = Self::count_hir_exprs(&hir);

        // Phase 5: Code Generation
        let code = match request.target {
            CompilationTarget::TypeScript => {
                let mut backend = TypeScriptBackend::new();
                backend.generate(&hir).map_err(|e| vec![e])?
            }
            CompilationTarget::JavaScript => {
                let mut backend = JavaScriptBackend::new();
                backend.generate(&hir).map_err(|e| vec![e])?
            }
            CompilationTarget::LLVM => {
                let mut backend = LLVMBackend::new();
                backend.generate(&hir).map_err(|e| vec![e])?
            }
        };

        let output_bytes = code.len();

        // Write to file if requested
        if let Some(output_path) = &request.output_path {
            fs::write(output_path, &code)
                .map_err(|e| {
                    vec![CompilationError::error(
                        format!("Failed to write output file: {}", e),
                        crate::token::Span::new(0, 0, 0, 0),
                        "",
                    )]
                })?;
        }

        Ok(CompilationResult {
            code,
            target: request.target,
            stats: CompilationStats {
                token_count,
                ast_node_count,
                hir_expr_count,
                output_bytes,
            },
        })
    }

    /// Compile Magma source to all three backends
    pub fn compile_all_targets(
        source: &str,
    ) -> Result<Vec<CompilationResult>, Vec<CompilationError>> {
        let mut results = Vec::new();

        for target in &[
            CompilationTarget::TypeScript,
            CompilationTarget::JavaScript,
            CompilationTarget::LLVM,
        ] {
            let request = CompilationRequest {
                source: source.to_string(),
                target: *target,
                output_path: None,
            };
            results.push(Self::compile(request)?);
        }

        Ok(results)
    }

    fn count_ast_nodes(program: &crate::ast::Program) -> usize {
        program.items.len()
    }

    fn count_hir_exprs(hir: &crate::hir::HirProgram) -> usize {
        hir.items.len()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_target_from_string_typescript() {
        assert_eq!(
            CompilationTarget::from_string("ts"),
            Some(CompilationTarget::TypeScript)
        );
        assert_eq!(
            CompilationTarget::from_string("typescript"),
            Some(CompilationTarget::TypeScript)
        );
    }

    #[test]
    fn test_target_from_string_javascript() {
        assert_eq!(
            CompilationTarget::from_string("js"),
            Some(CompilationTarget::JavaScript)
        );
        assert_eq!(
            CompilationTarget::from_string("javascript"),
            Some(CompilationTarget::JavaScript)
        );
    }

    #[test]
    fn test_target_from_string_llvm() {
        assert_eq!(
            CompilationTarget::from_string("llvm"),
            Some(CompilationTarget::LLVM)
        );
    }

    #[test]
    fn test_target_from_string_invalid() {
        assert_eq!(CompilationTarget::from_string("invalid"), None);
    }

    #[test]
    fn test_target_extension() {
        assert_eq!(CompilationTarget::TypeScript.extension(), "ts");
        assert_eq!(CompilationTarget::JavaScript.extension(), "js");
        assert_eq!(CompilationTarget::LLVM.extension(), "ll");
    }

    #[test]
    fn test_target_name() {
        assert_eq!(CompilationTarget::TypeScript.name(), "TypeScript");
        assert_eq!(CompilationTarget::JavaScript.name(), "JavaScript");
        assert_eq!(CompilationTarget::LLVM.name(), "LLVM IR");
    }

    #[test]
    fn test_compile_to_typescript() {
        let source = "fn test() : I32 => 42;";
        let request = CompilationRequest {
            source: source.to_string(),
            target: CompilationTarget::TypeScript,
            output_path: None,
        };
        let result = MagmaDriver::compile(request);
        assert!(result.is_ok());
        let result = result.unwrap();
        assert_eq!(result.target, CompilationTarget::TypeScript);
        assert!(result.code.contains("function test"));
    }

    #[test]
    fn test_compile_to_javascript() {
        let source = "fn test() : I32 => 42;";
        let request = CompilationRequest {
            source: source.to_string(),
            target: CompilationTarget::JavaScript,
            output_path: None,
        };
        let result = MagmaDriver::compile(request);
        assert!(result.is_ok());
        let result = result.unwrap();
        assert_eq!(result.target, CompilationTarget::JavaScript);
        assert!(result.code.contains("function test"));
    }

    #[test]
    fn test_compile_to_llvm() {
        let source = "fn test() : I32 => 42;";
        let request = CompilationRequest {
            source: source.to_string(),
            target: CompilationTarget::LLVM,
            output_path: None,
        };
        let result = MagmaDriver::compile(request);
        assert!(result.is_ok());
        let result = result.unwrap();
        assert_eq!(result.target, CompilationTarget::LLVM);
        assert!(result.code.contains("define i32 @test"));
    }

    #[test]
    fn test_compile_all_targets() {
        let source = "fn add(a : I32, b : I32) : I32 => a + b;";
        let results = MagmaDriver::compile_all_targets(source);
        assert!(results.is_ok());
        let results = results.unwrap();
        assert_eq!(results.len(), 3);

        // Verify all targets generated code
        assert!(results[0].code.contains("function add")); // TypeScript
        assert!(results[1].code.contains("function add")); // JavaScript
        assert!(results[2].code.contains("define i32 @add")); // LLVM
    }

    #[test]
    fn test_compilation_stats() {
        let source = "fn test() : I32 => 42;";
        let request = CompilationRequest {
            source: source.to_string(),
            target: CompilationTarget::TypeScript,
            output_path: None,
        };
        let result = MagmaDriver::compile(request).unwrap();
        
        assert!(result.stats.token_count > 0);
        assert!(result.stats.ast_node_count > 0);
        assert!(result.stats.hir_expr_count > 0);
        assert!(result.stats.output_bytes > 0);
    }

    #[test]
    fn test_complex_program_all_backends() {
        let source = r#"
            fn factorial(n : I32) : I32 => if n <= 1 { 1 } else { n * factorial(n - 1) };
            fn test() : I32 => factorial(5);
        "#;
        let results = MagmaDriver::compile_all_targets(source);
        assert!(results.is_ok());
        let results = results.unwrap();
        
        // All backends should produce output
        for result in &results {
            assert!(result.stats.output_bytes > 0);
            assert!(result.code.contains("factorial"));
        }
    }

    #[test]
    fn test_struct_compilation_all_backends() {
        let source = "struct Point { x : I32, y : I32 }";
        let results = MagmaDriver::compile_all_targets(source);
        assert!(results.is_ok());
        
        let results = results.unwrap();
        assert_eq!(results.len(), 3);
        
        // TypeScript should have interface
        assert!(results[0].code.contains("interface Point"));
        
        // JavaScript should have constructor
        assert!(results[1].code.contains("function Point"));
    }
}
